version: '3.8'

services:
  mysql:
    container_name: ms_mysql
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: mydatabase
    volumes:
      - mysql:/var/lib/mysql
    ports:
      - 3307:3306
    networks:
      - microservices-net
    restart: unless-stopped

  adminer:
    container_name: ms_adminer
    image: adminer
    ports:
      - 8080:8080
    networks:
      - microservices-net
    restart: unless-stopped

  mongodb:
    container_name: ms_mongo_db
    image: mongo:latest
    ports:
      - 27017:27017
    volumes:
      - mongo:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=1234
    networks:
      - microservices-net
    restart: unless-stopped
    # Thêm health check để đảm bảo MongoDB sẵn sàng
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 40s

  mongo-express:
    container_name: ms_mongo_express
    image: mongo-express
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=root
      - ME_CONFIG_MONGODB_ADMINPASSWORD=1234
      - ME_CONFIG_MONGODB_SERVER=ms_mongo_db
      # Thêm URL kết nối đầy đủ
      - ME_CONFIG_MONGODB_URL=mongodb://root:1234@ms_mongo_db:27017/
      # Thêm cấu hình basic auth (tùy chọn)
      - ME_CONFIG_BASICAUTH_USERNAME=admin
      - ME_CONFIG_BASICAUTH_PASSWORD=admin123
    networks:
      - microservices-net
    restart: unless-stopped
    # Đảm bảo mongo-express đợi MongoDB sẵn sàng
    depends_on:
      mongodb:
        condition: service_healthy

  mail-dev:
    container_name: ms_mail_dev
    image: maildev/maildev
    ports:
      - 1080:1080
      - 1025:1025
    networks:
      - microservices-net
    restart: unless-stopped

networks:
  microservices-net:
    driver: bridge

volumes:
  mysql:
  mongo: